version: 2.1

orbs:
  cli: circleci/circleci-cli@0.1.4

executors:
  cibuilds:
    docker:
      - image: cibuilds/base:2019.03

workflows:
  main:
    jobs:
      - test:
          filters:
            tags:
              # Simplified SemVer regex
              only: /^\d+\.\d+\.\d+$/
      - publish:
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              # Simplified SemVer regex
              only: /^\d+\.\d+\.\d+$/

jobs:
  test:
    executor: cibuilds
    steps:
      - checkout
      - cli/install
      - run:
          name: "Validate Orb config"
          command: circleci config pack src | circleci orb validate -
  publish:
    executor: cli/default
    steps:
      - checkout
      - run:
          name: "Publish orb via the CircleCI CLI"
          command: circleci config pack src | circleci orb publish - testimio/runner@${CIRCLE_TAG}
